{
 "title": "Banco - Control de Incidentes y LLM",
 "tags": [
  "banco",
  "observabilidad",
  "ollama"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS - Tasa de Peticiones por Segundo (API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{endpoint=\"/classify\"}[1m]))",
     "legendFormat": "RPS Global"
    }
   ]
  },
  {
   "title": "Distribución de Prioridades Detectadas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(classification_total) by (prioridad)",
     "legendFormat": "{{prioridad}}"
    }
   ]
  },
  {
   "title": "Consumo de CPU por Contenedor (API y Ollama)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"banco-api|api|ollama.*\"}[2m])) by (container)",
     "legendFormat": "{{container}} - CPU"
    }
   ]
  },
  {
   "title": "Consumo de RAM por Contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"banco-api|api|ollama.*\"}) by (container)",
     "legendFormat": "{{container}} - RAM"
    }
   ]
  },
  {
   "title": "Tiempo de Inferencia de Ollama Local (Latencia de IA)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(llm_inference_duration_seconds_bucket[5m])) by (le, prioridad))",
     "legendFormat": "P95 Latencia Inferencia {{prioridad}}"
    }
   ]
  }
 ]
}